In [1]:
import numpy as np

In [4]:
# buat matrix X berukuran 2x3 menggunakan numpy
x = np.array([[30, 2, 5], [4, 7, 11],])
x

array([[30,  2,  5],
       [ 4,  7, 11]])

In [5]:
# tampilkan ukuran dari matrix x
x.shape


(2, 3)

In [34]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
x[0:,]

array([[30,  2,  5],
       [ 4,  7, 11]])

In [10]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
x[:,1]

array([2, 7])

In [14]:
import torch

In [18]:
# buat matrix X berukuran 2x3 menggunakan pytorch
x_pt = torch.tensor([[30, 12, 15], [6, 10, 11],])
x_pt

tensor([[30, 12, 15],
        [ 6, 10, 11]])

In [19]:
# tampilkan ukuran dari matrix x
x_pt.shape

torch.Size([2, 3])

In [32]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
x_pt[0,:]

tensor([30, 12, 15])

In [33]:
# tampilkan seluruh elemen dari baris kedua dari matrix X

x_pt[:,1]

tensor([12, 10])

In [23]:
import tensorflow as tf

In [25]:
# buat matrix X berukuran 2x3 menggunakan tensorflow
x_tf = tf.Variable([[30, 12, 15], [6, 10, 11],])
x_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[30, 12, 15],
       [ 6, 10, 11]], dtype=int32)>

In [26]:
# tampilkan ukuran dari matrix x
tf.shape(x_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [35]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
x_tf[0,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([30, 12, 15], dtype=int32)>

In [36]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
x_tf[:,1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([12, 10], dtype=int32)>