In [5]:
import numpy as np

In [6]:
# buat vector x dengan ukuran 3x1
x = np.array([[25],
       [ 2],
       [ 5]])
x

array([[25],
       [ 2],
       [ 5]])

In [7]:
# hitung panjang vector x
len(x)

3

In [8]:
# tampilkan ukuran vector x
x.shape

(3, 1)

In [9]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [10]:
# akses elemen pertama dari vector x
x[0]

array([25])

In [11]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.ndarray

In [12]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([[25,  2,  5]])

In [13]:
# tampilkan ukuran dari vector x_t
x_t.shape

(1, 3)

In [28]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[22],
       [ 2],
       [ 8]])
y

array([[22],
       [ 2],
       [ 8]])

In [15]:
# tampilkan ukuran dari vector x_t
y.shape

(1, 3)

In [16]:
import torch
import tensorflow as tf

In [29]:
# lakukan soal nomor 2 menggunakan pytorch dan tensorflow
x_pt = torch.tensor([[50],
       [ 2],
       [ 10]])
x_t

tensor([[25],
        [ 2],
        [ 5]])

In [30]:
# lakukan transpose pada vector x dan simpan pada variabel x_pt.
x_pt = x_pt.T
x_pt

tensor([[50,  2, 10]])

In [31]:
# tampilkan ukuran dari vector x_t
x_pt.shape

torch.Size([1, 3])

In [32]:
# variabel y
y_pt = torch.tensor([[22],
       [ 12],
       [ 18]])
y_pt


tensor([[22],
        [12],
        [18]])

In [33]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y_pt = y_pt.T
y_pt

tensor([[22, 12, 18]])