In [2]:
import numpy as np

In [3]:
# buat vector x dengan ukuran 3x1
x = np.array([25, 15, 11])
x

array([25, 15, 11])

In [4]:
# hitung panjang vector x
len(x)

3

In [5]:
# tampilkan ukuran vector x
x.shape

(3,)

In [6]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [7]:
# akses elemen pertama dari vector x
x[0]

np.int64(25)

In [8]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.int64

In [9]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([25, 15, 11])

In [10]:
# tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [11]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[25, 2, 5]])
y

array([[25,  2,  5]])

In [12]:
# tampilkan ukuran dari vector x_t
y.shape

(1, 3)

In [13]:
import torch
import tensorflow as tf

In [16]:
# lakukan soal nomor 2 menggunakan pytorch dan tensorflow
x_pt = torch.tensor([25, 15, 11])
x_pt

tensor([25, 15, 11])

In [17]:
x_tf = tf.Variable([25, 15, 11])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25, 15, 11], dtype=int32)>